[package]
name = "sirena"
version = "0.0.1"
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"
description = "Digital audio signal processing, primitives, sounds."
repository = "https://github.com/zlosynth/sirena"
documentation = "https://docs.rs/sirena"
readme = "README.md"

[features]
default = ["std"]
std = ["rand", "rustfft"]

[dependencies]
rustfft = { version = "5.0", optional = true }
rand = { version = "0.8", optional = true }
micromath = "1.1"

[dev-dependencies]
approx = "0.4"
criterion = "0.3"
lazy_static = "1.4"
proptest = "1"

[[bench]]
name = "bench"
harness = false

[workspace]
members = [
  "pd",
]

[profile.release]
lto = true
panic = "abort"
opt-level = 3

[profile.bench]
debug = true
lto = true
opt-level = 3
