[package]
name = "sirena"
version = "0.0.1"
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Sounds!"
repository = "https://github.com/zlosynth/sirena"
documentation = "https://docs.rs/sirena"
readme = "README.md"

[dependencies]
meval = "0.2"
graphity = "2.0"
cpal = "0.13"
gazpatcho = { path = "../gazpatcho" }
lazy_static = "1.4"

[dev-dependencies]
approx = "0.4"

[profile.release]
debug = true
