[package]
name = "sirena"
version = "0.0.1"
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Sounds!"
repository = "https://github.com/zlosynth/sirena"
documentation = "https://docs.rs/sirena"
readme = "README.md"

[features]
default = ["std"]
std = ["rand", "rustfft"]

[dependencies]
rustfft = { version = "5.0", optional = true }
rand = { version = "0.8", optional = true }

[dev-dependencies]
approx = "0.4"

[workspace]
members = [
  "pd",
  "ui",
]

[profile.release]
lto = true
panic = "abort"
