[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.dev]
workspace = false
dependencies = ["format-toml"]
run_task = { name = "dev-workspace", fork = true }

[tasks.dev-workspace]
dependencies = ["format", "clippy", "build", "check-arm", "test"]

[tasks.ci]
workspace = false
dependencies = ["print-env-flow", "check-toml"]
run_task = { name = "ci-workspace", fork = true }

[tasks.ci-workspace]
dependencies = [
  "check-format",
  "clippy",
  "build",
  "check-arm",
  "test",
  "test-slow",
]

# TODO: Drop this once https://github.com/sagiegurari/cargo-make/pull/697 is merged
[tasks.format-toml]
condition = { env_set = ["CARGO_MAKE_FORMAT_TOML_FILES"] }
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = [
  "--help",
] }
command = "taplo"
args = [
  "format",
  "${CARGO_MAKE_FORMAT_TOML_FILES}",
  "@@split(CARGO_MAKE_FORMAT_TOML_ARGS, )",
]

[tasks.check-toml]
env = { CARGO_MAKE_FORMAT_TOML_ARGS = "--check" }
run_task = { name = "format-toml" }

[tasks.clippy]
env = { CARGO_MAKE_CLIPPY_ARGS = "--tests --benches -- -Dclippy::all -Dclippy::pedantic" }

[tasks.check-arm]
command = "cargo"
args = ["check", "--all", "--target", "thumbv7em-none-eabihf"]

[tasks.test-slow]
env = { CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--all --all-features -- --ignored" }
run_task = { name = "test" }
